sudo: required
language: cpp

branches:
  only: master

matrix:
  include:
    - os: linux
      env: CXX=/usr/bin/g++-7
      sudo: required
      dist: bionic
      compiler: gcc
      before_install: 
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo chmod +x tools/travis/linux/install.sh
      install: travis_wait 40 "./tools/travis/linux/install.sh"
      before_script:
        - sudo chmod +x tools/travis/linux/build.sh
      script: "./tools/travis/linux/build.sh"
